### ISSUE TITLE
Logout button no longer works

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp-module-authorize#14]
The template has a logout button but the `LogoutURL` is constructed as a _login_ url without ReturnTo parameter:

https://github.com/simplesamlphp/simplesamlphp-module-authorize/blob/bb2436f9310b17a520194e63ca4842b14d3f328a/src/Controller/Authorize.php#L68

so this fails with a `Missing ReturnTo parameter` error when clicked.

Probably the same issue applies to the cardinality module.

**Comment by tvdijen** [comment]
Can we use `$state['Source']['auth']` to get the authsource (`Auth\Source::getById()`) and call `logout()` on it?

**Comment by thijskh** [comment]
The modules now just render a button with a link to what was previously (in 0.9): `core/authenticate.php?as=...&logout`. I don't think that target exists anymore. What you say might be possible but it would need a separate route in the module to invoke that when the button is pressed.

**Comment by tvdijen** [comment]
There is `core/logout/{as}` ?

**Comment by thijskh** [comment]
One challenge there is that it requires some ReturnTo parameter to be specified and I'm unsure what a good value would be.

**Comment by tvdijen** [comment]
I guess `frontpage.redirect` is the perfect value for that?

**Comment by dbollaer** [comment]
Hello, is there any update about this issue?

**Comment by thijskh** [comment]
We've been stretched for time due to the holidays, if you can help with a fix that'd be great!

**Comment by tvdijen** [comment]
@dbollaer I'm not using this module myself, so it's difficult for me to test..
The fix in #16 is theoretical, but could you give it a try?

**Comment by dbollaer** [comment]
@tvdijen thank you very much. I validated the bug fix. It works 👍
