### ISSUE TITLE
Show unauthorised users with which account they are logged in 

### ISSUE THREAD

**Issue by dbollaer** [simplesamlphp/simplesamlphp-module-authorize#19]
Our users can log in with an Entra ID guest account, which is not allowed to access our federation.
Some users do not know with which account they are logged in. So they assume it's their work account.

By showing the user's their email address, we can provide them with enough information, so they can understand their situation and change to the correct account.

I also thought about showing their username, but we are trying to step away from this.
As alternative, we can also block users in Entra ID, but this user experience is really bad. The user gets a cryptic message, which is barely acceptable for internal users, and for external users without proper context is a night mare.

If you agree with this feature, could you please describe which changes that need to be done and I'll make a PR.

Thank you

**Comment by tvdijen** [comment]
Hi Danny!  This one should be even easier.  It's just a matter of adding this to the twig-template. The attributes from their first login-attempt are available in the state variable ($state['Attributes']).

**Comment by dbollaer** [comment]
Hi @tvdijen, I was more wondering about the small details, for example:

I would introduce a new config parameter: show_user_attribute.
If show_user_attribute is empty nothing happens, if it's filled in, I will show the first attribute value.

The value of show_user_attribute will be used in a new message, this way it will have minimal impact on people who are using the module.

As alternative of adding a new message, I can add it to custom message text. What do you prefer?

**Comment by tvdijen** [comment]
This all sounds good to me!
A new message with a placeholder for the username would be fine!
