### ISSUE TITLE
Missing "is defined" in twig template

### ISSUE THREAD

**Issue by msalle** [simplesamlphp/simplesamlphp-module-authorize#6]
In [templates/authorize_403.twig line 5](
https://github.com/simplesamlphp/simplesamlphp-module-authorize/blob/master/templates/authorize_403.twig#L5) there is a missing ` is defined`
This causes a `Twig\Error\RuntimeError: Variable "reject_msg" does not exist.` and corresponding UNHANDLEDEXCEPTION.
Note that there are more of these, e.g. line 10 in the same file.
I'm using SimpleSAMLPHP 1.19.0

**Comment by tvdijen** [comment]
Thanks @msalle , I've tagged a new release for this module and will make sure it ends up in 1.19.1
